"""
Email conversation export via AWS SES.
"""
import logging
from datetime import datetime

import boto3
from botocore.exceptions import ClientError

logger = logging.getLogger(__name__)

EMAIL_FROM = "chatbot@edopt.org"
AWS_REGION = "us-east-1"


def send_conversation_email(to_email: str, messages: list):
    """Send a conversation transcript to the user's email."""
    # Build plain-text body
    lines = [
        "EdOpt Navigator — Your Conversation Summary",
        "=" * 50,
        "",
    ]
    for msg in messages:
        role = "You" if msg["role"] == "user" else "EdOpt Navigator"
        timestamp = ""
        if msg.get("created_at"):
            try:
                dt = datetime.fromisoformat(msg["created_at"])
                timestamp = f" ({dt.strftime('%B %d, %Y %I:%M %p')})"
            except (ValueError, TypeError):
                pass
        lines.append(f"--- {role}{timestamp} ---")
        lines.append(msg["content"])
        lines.append("")

    lines.extend([
        "---",
        "This conversation was generated by the EdOpt Navigator at chatbot.edopt.org",
        "Visit edopt.org to explore more education options in New Hampshire.",
        "",
        "Questions? Contact EdOpt at edopt.org",
    ])

    body_text = "\n".join(lines)
    subject = "Your EdOpt Navigator Conversation"

    ses = boto3.client("ses", region_name=AWS_REGION)
    try:
        ses.send_email(
            Source=EMAIL_FROM,
            Destination={"ToAddresses": [to_email]},
            Message={
                "Subject": {"Data": subject, "Charset": "UTF-8"},
                "Body": {
                    "Text": {"Data": body_text, "Charset": "UTF-8"},
                },
            },
        )
        logger.info(f"Conversation emailed to {to_email}")
    except ClientError as e:
        logger.error(f"SES send failed: {e}")
        raise
